# kubectl apply -f <*.yaml>
# kubectl -n kubernetes-dashboard create token admin-user1

apiVersion: v1
kind: ServiceAccount
metadata:
    name: admin-user1
    namespace: kubernetes-dashboard
#automountServiceAcconutToken: true

---

#binding service-account with role in the cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
#- apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: admin-user1
    namespace: kubernetes-dashboard